data-directory = "data/"
scripts-directory = "examples/scripts/"

flush-interval = 5

[tags]
source = "cernan"

[sources]
  [sources.internal]
  forwards = ["sinks.console"]

  [sources.graphite.primary]
  port = 2004
  forwards = ["filters.delay.smallish"]
  # forwards = ["sinks.console"]

[filters]
  [filters.delay.smallish]
  tolerance = 2
  forwards = ["sinks.console"]
  # forwards = ["filters.flush_boundary.smallish"]

  # [filters.flush_boundary.smallish]
  # tolerance = 4
  # forwards = ["sinks.console"]

[sinks]
  [sinks.console]
