data-directory = "data/"
scripts-directory = "examples/scripts/"

flush-interval = 5

[tags]
source = "cernan"

[sources]
  [sources.internal]
  # forwards = ["filters.delay.two_seconds"]
  forwards = ["sinks.console"]

  [sources.graphite.primary]
  port = 2004
  forwards = ["filters.delay.two_seconds"]

[filters]
  [filters.delay.two_seconds]
  tolerance = 2
  forwards = ["sinks.console"]

#   [filters.flush_boundary.four_seconds]
#   tolerance = 4
#   forwards = ["sinks.console", "sinks.null"]

[sinks]
  [sinks.console]
